server:
  port: 8803
spring:
  data: 
    neo4j:
      username: neo4j
      password: neo4j@wankeauto.com
      uri: http://192.168.2.13:7474
  redis:
    database: 0
    host: 192.168.2.13
    port: 8811
    password: Jhf&*d93jfdKJSf
    pool:
      max-active: 400
      max-wait: 10000
      max-idle: 100
      min-idle: 0
    timeout: 0
	datasource:
		type: com.alibaba.druid.pool.DruidDataSource
		url: jdbc:mysql://172.18.12.133:3306/sgool?useUnicode=true&characterEncoding=utf-8
		username: wanke
		password: 5j1#H!^d
		driverClassName: com.mysql.jdbc.Driver
	jpa: 
		database: mysql