server:
  port: 8802
spring: 
	datasource:
		type: com.alibaba.druid.pool.DruidDataSource
		url: jdbc:mysql://172.18.12.133:3306/sgool?useUnicode=true&characterEncoding=utf-8
		username: wanke
		password: 5j1#H!^d
		driverClassName: com.mysql.jdbc.Driver
	jpa: 
		database: mysql